apiVersion: apps/v1
kind: Deployment
metadata:
  name: "readabledemo"
  namespace: rbm
spec:
  selector:
    matchLabels:
      app: "readabledemo"
  template:
    metadata:
      labels:
        app: "readabledemo"
    spec:
      containers:
        - name: "readabledemo"
          image: "q1ltd/readabledemo:latest"
          ports:
            - name: http
              containerPort: 8087
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8087
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8087
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: readabledemo
  namespace: rbm
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8087
  selector:
    app: readabledemo
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-readabledemo
  namespace: rbm
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`readabledemo.example.com`)
      kind: Rule
      services:
        - name: readabledemo
          port: 8087
  tls:
    certResolver: myresolver
